---
include:
  # - board: eyelash_sofle_left
  #    shield: nice_view
  - board: eyelash_sofle_right
    #   shield: nice_view_custom
    shield: nice_view nice_view_gem
  - board: eyelash_sofle_left
    shield: nice_view nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_NICE_VIEW_GEM_ANIMATION=n
    artifact-name: eyelash_sofle_studio_left
  - board: nice_nano_v2
    shield: settings_reset
